spring:
  application:
    name: justonebite
  springdoc:
    auto-response-code: false
    swagger-ui:
      tags-sorter: alpha
      operations-sorter: alpha

  datasource:
    url: jdbc:postgresql://postgres:5432/just_one_bite
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # show-sql: true

  data:
    redis:
      host: redis
      port: 6379
      username: default
      password: ${REDIS_PASSWORD}

logging:
  level:
    root: DEBUG
    
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
